### ISSUE TITLE
Feature request: multiple file output

### ISSUE THREAD

**Issue by imvudude** [Notuom/ytmd-obs-output#1]
Hey. Loving the script. I was just wondering if the output could support outputting the song title, album and artist as seperate text files.

**Comment by Notuom** [comment]
Hey! Glad you enjoy it. Yes, that's definitely possible, let me see what I can do. I'm thinking we'll add a new config which allows multiple output files and then you can output whatever combination you need in each file.

**Comment by Notuom** [comment]
Hi @imvudude, I've implemented this request and updated the documentation. I've also added config validation so the script will tell you if something's not right in the config when it starts. Let me know if that works for you!

**Comment by imvudude** [comment]
Amazing! works like a charm. Thanks man! Now if only YTMD would actually output album titles...
