### ISSUE TITLE
Feature Request: timeout paused videos

### ISSUE THREAD

**Issue by frankiesimon** [Notuom/ytmd-obs-output#2]
First off - what a great little tool - awesome job creating it!

I see that the YTMD SDK also has a Player object so it's possible to know whether there's a song and whether it's paused.

It would be cool to have a sort of "timeout" mechanism that clears the text/album art files if there is no video playing for a certain amount of time.

My scenario - I'd like to be using this for a sort of indication of a video I'm currently watching - but I don't want it to be displayed forever if I paused the video seeing as there's no real way to "clear" YTMD.

**Comment by Notuom** [comment]
Hey @frankiesimon, thanks for the suggestion and I'm glad the tool has been useful to you!

I've implemented this using a new configuration option called `removeTrackAfterPausedForMs` (not set by default). If you add this with a value in milliseconds, it should now do what you asked. Let me know if you have any issues!
